### PR TITLE
Add language to specify fill value

### LINKED ISSUE #23: Custom fill values
Is it in scope to allow users to choose their own fill value (sometimes called implicit value, usually zero)?

### PR DESCRIPTION
**Pull request by willow-ahrens**
fixes #23

### CODE REVIEW

**Comment by willow-ahrens** [comment]
@eriknw @jim22k I believe there was consensus on this, requesting review/merge

**Comment by jim22k** [comment]
> whose single element defines the fill (zero) value of the sparse tensor,
or the value of the array at indices not otherwise specified by the sparse
tensor structure

Can we change this to
"whose single element defines the value of indices not specified
by the sparse tensor structure"?

I want to make absolutely sure that no one can interpret the fill value as overwriting an explicit zero.

**Comment by willow-ahrens** [comment]
Yep! I updated the file.

**Review by jim22k — APPROVED** [review]

**Comment by jim22k** [comment]
Looks like there is a merge conflict. Once that is fixed, this should okay to merge.

**Pull request merged**
